require("jaguilera.plugins-setup") -- should be at the top
require("jaguilera.core.options")
require("jaguilera.core.keymaps")
require("jaguilera.core.colorscheme")
require("jaguilera.plugins.comment")
require("jaguilera.plugins.nvim-tree")
require("jaguilera.plugins.lualine")
require("jaguilera.plugins.telescope")
require("jaguilera.plugins.nvim-cmp")
require("jaguilera.plugins.lsp.mason")
require("jaguilera.plugins.lsp.lspsaga")
require("jaguilera.plugins.lsp.lspconfig")
require("jaguilera.plugins.lsp.null-ls")
require("jaguilera.plugins.autopairs")
require("jaguilera.plugins.treesitter")
require("jaguilera.plugins.gitsigns")
require("jaguilera.plugins.bufferline")
require("jaguilera.plugins.colorizer")
require("jaguilera.plugins.neural")
require("jaguilera.plugins.indent-blankline")
-- require("jaguilera.plugins.tabnine")
